# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/fos_cfd_ram/fos_cfd_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fos_cfd_ram || ORIG_REF_NAME==fos_cfd_ram} -quiet] -quiet
