# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/backup/FPGA/Project/Project.cache/wt [current_project]
set_property parent.project_path C:/backup/FPGA/Project/Project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
set_property ip_repo_paths c:/backup/FPGA/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo c:/backup/FPGA/Project/Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/backup/FPGA/Project/Project.srcs/sources_1/ip/SinglePass_CCL_0/Algorithm.srcs/sources_1/ip/stack.coe
read_verilog -library xil_defaultlib C:/backup/FPGA/Project/Project.srcs/sources_1/new/fos_cfd.v
read_ip -quiet C:/backup/FPGA/Project/Project.srcs/sources_1/ip/fos_cfd_ram/fos_cfd_ram.xci
set_property used_in_implementation false [get_files -all c:/backup/FPGA/Project/Project.srcs/sources_1/ip/fos_cfd_ram/fos_cfd_ram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fos_cfd -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fos_cfd.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fos_cfd_utilization_synth.rpt -pb fos_cfd_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
